<?php

declare(strict_types=1);

namespace XPHP\TestSupport;

use Composer\Autoload\ClassLoader;
use PhpParser\ParserFactory;
use PhpParser\PrettyPrinter\Standard as StandardPrinter;
use RuntimeException;
use XPHP\FileSystem\FileFinder\NativeFileFinder;
use XPHP\FileSystem\FileReader\NativeFileReader;
use XPHP\FileSystem\FileWriter\NativeFileWriter;
use XPHP\Transpiler\Monomorphize\Compiler;
use XPHP\Transpiler\Monomorphize\Registry;
use XPHP\Transpiler\Monomorphize\SpecializedClassGenerator;
use XPHP\Transpiler\Monomorphize\Specializer;
use XPHP\Transpiler\Monomorphize\XphpSourceParser;

/**
 * Compiles a tracked `.xphp` fixture into a throwaway temp dir, then
 * lets tests drive the generated PHP through a registered autoloader.
 * Lifecycle is owned by the caller (`setUpBeforeClass` /
 * `tearDownAfterClass`, or per-method `setUp` / `tearDown`).
 *
 * Process-isolation contract: PHP has no `class_unload`, so a verify
 * file that autoloads `App\…\…` classes leaks them into the symbol
 * table for the rest of the PHPUnit process. Two tests that each
 * load the same FQN from different temp dirs would silently share
 * the first run's class definition. Mark every verify-loading test
 * `#[RunInSeparateProcess]` (or use `setUpBeforeClass` for an entire
 * `TestCase` that shares one fixture across methods).
 *
 * Failure attribution: when a verify file calls `Assert::*` and it
 * fails, the exception's throw site is the verify file (`path:line`),
 * and the `require` frame is the calling `testFoo` method — PHPUnit
 * reports both.
 *
 * Usage:
 *   $fixture = CompiledFixture::compile($sourceDir, 'array-sugar');
 *   $fixture->registerAutoload('App\\ArraySugar\\');
 *   try {
 *       require __DIR__ . '/../../fixture/compile/array_sugar/verify/foo.php';
 *   } finally {
 *       $fixture->cleanup();
 *   }
 */
final class CompiledFixture
{
    private ?ClassLoader $loader = null;

    private function __construct(
        public readonly string $workDir,
        public readonly string $targetDir,
        public readonly string $cacheDir,
    ) {
    }

    /**
     * Compile the fixture under `$sourceDir` into a fresh temp work
     * dir tagged with `$tag` (for ergonomic /tmp paths).
     */
    public static function compile(string $sourceDir, string $tag = 'xphp'): self
    {
        $resolved = realpath($sourceDir)
            ?: throw new RuntimeException("missing fixture source: {$sourceDir}");

        $workDir = sys_get_temp_dir() . '/xphp-' . $tag . '-' . uniqid('', true);
        if (!mkdir($workDir, 0o755, true) && !is_dir($workDir)) {
            throw new RuntimeException("could not create work dir: {$workDir}");
        }

        $self = new self(
            $workDir,
            $workDir . '/dist',
            $workDir . '/.xphp-cache',
        );
        try {
            $self->runCompiler($resolved);
        } catch (\Throwable $e) {
            self::rrmdir($workDir);
            throw $e;
        }
        return $self;
    }

    /**
     * Register a Composer autoloader that resolves the given user PSR-4
     * prefixes to `$targetDir` and the generated-namespace prefix to
     * `$cacheDir/Generated`. Idempotent: calling twice replaces the
     * previously registered loader for this fixture.
     */
    public function registerAutoload(string ...$userPrefixes): void
    {
        $this->loader?->unregister();
        $loader = new ClassLoader();
        foreach ($userPrefixes as $prefix) {
            $loader->addPsr4(rtrim($prefix, '\\') . '\\', $this->targetDir);
        }
        $loader->addPsr4(
            Registry::GENERATED_NAMESPACE_PREFIX . '\\',
            $this->cacheDir . '/Generated',
        );
        $loader->register();
        $this->loader = $loader;
    }

    /**
     * Map a generated FQN back to its on-disk file inside `$cacheDir`.
     * Useful for tests that read the generated bytes directly (snapshots,
     * syntax checks) rather than going through the autoloader.
     */
    public function fqnToPath(string $fqn): string
    {
        $prefix = Registry::GENERATED_NAMESPACE_PREFIX . '\\';
        $rel = str_starts_with($fqn, $prefix) ? substr($fqn, strlen($prefix)) : $fqn;
        return $this->cacheDir . '/Generated/' . str_replace('\\', '/', $rel) . '.php';
    }

    /**
     * Unregister the autoloader (if any) and rm -rf the work dir.
     */
    public function cleanup(): void
    {
        $this->loader?->unregister();
        $this->loader = null;
        self::rrmdir($this->workDir);
    }

    private function runCompiler(string $sourceDir): void
    {
        $phpParser = (new ParserFactory())->createForHostVersion();
        $printer = new StandardPrinter();
        $writer = new NativeFileWriter();
        $compiler = new Compiler(
            new NativeFileReader(),
            $writer,
            new XphpSourceParser($phpParser),
            new Specializer(),
            new SpecializedClassGenerator($printer, $writer),
            $printer,
        );
        $sources = (new NativeFileFinder())
            ->find($sourceDir)
            ->filter(static fn (string $f): bool => str_ends_with($f, '.xphp'));
        $compiler->compile($sources, $sourceDir, $this->targetDir, $this->cacheDir);
    }

    private static function rrmdir(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }
        foreach (scandir($dir) ?: [] as $entry) {
            if ($entry === '.' || $entry === '..') {
                continue;
            }
            $path = $dir . '/' . $entry;
            is_dir($path) ? self::rrmdir($path) : unlink($path);
        }
        rmdir($dir);
    }
}
